apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-ingress-from-host
  namespace: {{ .Release.Namespace }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium
      namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - host
    - remote-node
