apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-ingress-from-host
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - host
    - remote-node
