apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: cilium
        git:
          depth: 1
          url: https://github.com/cilium/cilium
          ref: "v1.16.1"
        includePaths:
          - install/kubernetes/**/*
          - Makefile.defs
          - Makefile.quiet
          - VERSION
  - path: helm
    contents:
      - path: .
        directory:
          path: vendor/cilium/install/kubernetes
        ignorePaths:
          - cilium/Chart.yaml
          - cilium/Chart.lock
          - cilium/files/policies/*
          - cilium/templates/default-policies/*
          - cilium/templates/extra-policies/*
          - cilium/templates/**/networkpolicy.yaml
          - cilium/templates/**/podsecuritypolicy.yaml
          - cilium/charts/cilium-giantswarm-cni-customconf/*.yaml
          - cilium/charts/cilium-giantswarm-cni-customconf/README.md
          - cilium/charts/cilium-giantswarm-cni-customconf/values.schema.json
          - cilium/charts/cilium-giantswarm-cni-customconf/templates/cilium-cni-configmap.yaml
