apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: cilium
        git:
          depth: 1
          url: https://github.com/cilium/cilium
          ref: &version "v1.16.5"
        includePaths:
          - install/kubernetes/**/*
          - Makefile.defs
          - Makefile.quiet
          - VERSION
      # fetch chart for final release digests from values.yaml
      - path: cilium-chart
        helmChart:
          name: cilium
          version: *version
          repository:
            url: https://helm.cilium.io/
        includePaths:
          - values.yaml
  - path: helm
    contents:
      - path: .
        directory:
          path: vendor/cilium/install/kubernetes
        ignorePaths:
          - cilium/Chart.yaml
          - cilium/Chart.lock
          - cilium/templates/**/networkpolicy.yaml
          - cilium/templates/**/podsecuritypolicy.yaml
          - cilium/charts/cilium-giantswarm-cni-customconf/*.yaml
          - cilium/charts/cilium-giantswarm-cni-customconf/README.md
          - cilium/charts/cilium-giantswarm-cni-customconf/values.schema.json
          - cilium/charts/cilium-giantswarm-cni-customconf/templates/cilium-cni-configmap.yaml
