apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: cilium
        git:
          url: https://github.com/giantswarm/cilium
          ref: "gs-remove-nulls-helm-values"
        includePaths:
          - install/kubernetes/cilium/**/*
  - path: helm/cilium
    contents:
      - path: .
        directory:
          path: vendor/cilium/install/kubernetes/cilium
