apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: cilium
        git:
          url: https://github.com/cilium/cilium
          ref: v1.13.6
        includePaths:
          - install/kubernetes/cilium/**/*
  - path: helm/cilium2/templates
    contents:
      - path: .
        directory:
          path: vendor/cilium/install/kubernetes/cilium/templates
