{{- $eniConf := dict "first-interface-index" .Values.eni.firstInterfaceIndex -}}
{{- with .Values.eni.excludeInterfaceTags -}}
{{- $_ := set $eniConf "exclude-interface-tags" . -}}
{{- end -}}
{{- with .Values.eni.securityGroupTags -}}
{{- $_ := set $eniConf "security-group-tags" . -}}
{{- end -}}
{{- with .Values.eni.subnetTags -}}
{{- $_ := set $eniConf "subnet-tags" . -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-cni-configuration
  namespace: {{ .Release.Namespace }}
data:
  cni-config: |-
      {
        "cniVersion":"0.3.1",
        "name":"cilium",
        "plugins": [
          {
            "cniVersion":"0.3.1",
            "type":"cilium-cni",
            "eni": {{ mustToJson $eniConf }}
          }
        ]
      }
