{{- if and (or .Values.hubble.enabled .Values.hubble.ui.standalone.enabled) .Values.hubble.ui.enabled .Values.hubble.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    k8s-app: hubble-ui
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/part-of: cilium
  name: hubble-ui
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - ports:
        - port: 8081
          protocol: TCP
  podSelector:
    matchLabels:
      k8s-app: hubble-ui
      app.kubernetes.io/name: hubble-ui
      app.kubernetes.io/part-of: cilium
      {{- with .Values.hubble.ui.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  policyTypes:
    - Ingress
{{- end }}
