{{- if .Values.hubble.ui.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    k8s-app: hubble-ui
  name: hubble-ui
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s-app: hubble-ui
      app.kubernetes.io/name: hubble-ui
      app.kubernetes.io/part-of: cilium
      {{- with .Values.hubble.ui.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  egress:
    - toEntities:
        - cluster
        - kube-apiserver
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "8081"
{{- end }}
