{{- if and .Values.hubble.enabled .Values.hubble.relay.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    k8s-app: hubble-relay
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s-app: hubble-relay
  egress:
    - toEntities:
        - cluster
        - kube-apiserver
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "{{ .Values.hubble.relay.listenPort }}"
            - port: "{{ .Values.hubble.relay.prometheus.port }}"
{{- end }}
